### ISSUE TITLE
As a glimmer component?

### ISSUE THREAD

**Issue by arthur5005** [ef4/ember-set-body-class#10]
I've got to ask, how does the community support components like this going forward, where there's a dependency on lifecycle hooks, but no underlying dom? 

As a glimmer component you don't get that ability.

It's been bugging me, because I feel we `traded one for the other` if you know what I mean. Are Ember components going to live on in perpetuity as `a slower, but more feature rich` component?

**Comment by ef4** [comment]
I think the most likely answer is
https://github.com/emberjs/rfcs/pull/567

This addon is a good motivating example because it synchronizes ember state
out onto non ember controlled DOM.

**Comment by arthur5005** [comment]
Ah, this is it. I should check the RFCs more often! 

Thanks!

**Comment by Turbo87** [comment]
#54 converted the component to a helper, so this should be relatively future-proof for now :)
