### ISSUE TITLE
Dynamically update body classes as param value changes 

### ISSUE THREAD

**Issue by billdami** [ef4/ember-set-body-class#3]
I've noticed that if a bound property is passed to `set-body-class`, the body classes will not dynamically update to the new value, the component has to be destroyed and re-rendered/initialized. Is this something that could be added? 

I have a use case where we want to use `{{set-body-class}}` in the application template, and is bound to the router's `currentPath` value (setting a dasherized class name on the body that reflects the currently viewed page route). However it only works for the initially rendered route.

**Comment by ef4** [comment]
Yes, this could be added, seems reasonable.
